### ISSUE TITLE
Error: Command failed: convert: unrecognized dither method `-background'

### ISSUE THREAD

**Issue by GoodnessJSON** [sibbl/hass-lovelace-kindle-screensaver#112]
Hi there,

Just updated to v1.0.7 and love the new configs. Unfortunately the add-on now crashes with every start with this error:

``` 
Converting rendered screenshot of http://192.168.1.50:8123/dashboard-kindle/0?kiosk to grayscale png...
/app/node_modules/gm/lib/command.js:301
          err = new Error('Command failed: ' + stderr);
                ^

Error: Command failed: convert: unrecognized dither method `-background' @ error/convert.c/ConvertImageCommand/1422.

    at ChildProcess.onExit (/app/node_modules/gm/lib/command.js:301:17)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:517:28)
    at Pipe.<anonymous> (node:net:350:12) {
  code: 1,
  signal: null
}
```

I've tried toggling the Dither and Gamma settings but it makes no difference. Can this be looked at? Thanks so much for the great project!

**Comment by andyb2000** [comment]
Yep, spotted this after testing and talking to @sibbl about another issue with env's so looks like it's due to the line 308 in index.js (      .dither(pageConfig.dither))

I may get time tomorrow to take a quick look.

**Comment by sibbl** [comment]
The cause of this might be that we Dockerfile uses imagemagick instead of graphicsmagick. While the [used npm module `gm`](https://www.npmjs.com/package/gm) says to be compatible with both, it doesn't seem to support the differences in the `-dither` parameter. While `+dither` works for both, [the `-dither` parameter requires the name of the dither algorithm to use in imagemagick](https://legacy.imagemagick.org/Usage/quantize/#dither_how), while [graphicsmagick only uses it as a toggle](http://www.graphicsmagick.org/GraphicsMagick.html#details-dither).

Maybe it's worth to give Graphicsmagick another try in the Dockerfile but I'm not sure what other incompatibilities will occur.
An alternative would be to open an issue in the gm npm package repository.
Finally, we could also just use the "custom arguments" feature of the gm npm package to support `-dither ALGORITHM` and ´+dither` by our own. That's probably what I'd prefer.

**Comment by sibbl** [comment]
Thanks for the confirmation and sorry that it happened in the first place!
